### PR TITLE
week1-assignment

### PR DESCRIPTION
**Pull request by XanderSchevenhoven**
## Release Notes

- **New Features**
  - Introduced a new Databricks asset bundle configuration.
  - Added a structured notebook for data preprocessing and machine learning model training.
  - New configuration files for project parameters and model settings.

- **Improvements**
  - Updated CI workflow for better Python setup and dependency management.
  - Enhanced visualization functions for model results and feature importance.

- **Bug Fixes**
  - Cleaned up formatting in the README file.

- **Chores**
  - Added `.databricks` to `.gitignore` to prevent tracking of specific files.

### CODE REVIEW

**Review by basakeskili — APPROVED** [review]
Looks really nice, thanks!

**Comment by XanderSchevenhoven** [comment]
> Looks really nice, thanks!

Thanks! Sorry for the extra commits, just experimenting with CodeRabbit. Looks very promising! May have to see whether I can have it enabled for my organization :)

**Review by mvechtomova — APPROVED** [review]
nice work! the only comment I would have regarding the project structure: nicer to put folder power in folder src to reflect that it is the source folder for the package

**Comment by XanderSchevenhoven** [comment]
Ah okay, good tip @mvechtomova . The reason I structured it this way is because it works better with Git Repos / Folders in Databricks (which is what I usually use when developing instead of VSCode). The package in the root path is automatically recognized whereas I don't think it would be if it's in the /src folder?

**Pull request merged**
